-- Sippi Lights — seed inventory_items from src/data/inventory.ts
-- Run after migrations (supabase db reset runs this automatically, or paste into SQL editor).
truncate table inventory_items;

insert into inventory_items (name, category, char_value, finish, price, qty_owned, active) values
  ('A', 'letter', 'A', 'white', 70, 1, true),
  ('B', 'letter', 'B', 'white', 70, 1, true),
  ('C', 'letter', 'C', 'white', 70, 1, true),
  ('D', 'letter', 'D', 'white', 70, 1, true),
  ('E', 'letter', 'E', 'white', 70, 1, true),
  ('F', 'letter', 'F', 'white', 70, 1, true),
  ('G', 'letter', 'G', 'white', 70, 1, true),
  ('H', 'letter', 'H', 'white', 70, 1, true),
  ('I', 'letter', 'I', 'white', 70, 1, true),
  ('J', 'letter', 'J', 'white', 70, 1, true),
  ('K', 'letter', 'K', 'white', 70, 1, true),
  ('L', 'letter', 'L', 'white', 70, 1, true),
  ('M', 'letter', 'M', 'white', 70, 1, true),
  ('N', 'letter', 'N', 'white', 70, 1, true),
  ('O', 'letter', 'O', 'white', 70, 1, true),
  ('P', 'letter', 'P', 'white', 70, 1, true),
  ('Q', 'letter', 'Q', 'white', 70, 1, true),
  ('R', 'letter', 'R', 'white', 70, 1, true),
  ('S', 'letter', 'S', 'white', 70, 1, true),
  ('T', 'letter', 'T', 'white', 70, 1, true),
  ('U', 'letter', 'U', 'white', 70, 1, true),
  ('V', 'letter', 'V', 'white', 70, 1, true),
  ('W', 'letter', 'W', 'white', 70, 1, true),
  ('X', 'letter', 'X', 'white', 70, 1, true),
  ('Y', 'letter', 'Y', 'white', 70, 1, true),
  ('Z', 'letter', 'Z', 'white', 70, 1, true),
  ('0', 'number', '0', 'black', 70, 1, true),
  ('0', 'number', '0', 'white', 70, 1, true),
  ('1', 'number', '1', 'black', 70, 1, true),
  ('1', 'number', '1', 'white', 70, 1, true),
  ('2', 'number', '2', 'black', 70, 1, true),
  ('2', 'number', '2', 'white', 70, 1, true),
  ('3', 'number', '3', 'black', 70, 1, true),
  ('3', 'number', '3', 'white', 70, 1, true),
  ('4', 'number', '4', 'black', 70, 1, true),
  ('4', 'number', '4', 'white', 70, 1, true),
  ('5', 'number', '5', 'black', 70, 1, true),
  ('5', 'number', '5', 'white', 70, 1, true),
  ('6', 'number', '6', 'black', 70, 1, true),
  ('6', 'number', '6', 'white', 70, 1, true),
  ('7', 'number', '7', 'black', 70, 1, true),
  ('7', 'number', '7', 'white', 70, 1, true),
  ('8', 'number', '8', 'black', 70, 1, true),
  ('8', 'number', '8', 'white', 70, 1, true),
  ('9', 'number', '9', 'black', 70, 1, true),
  ('9', 'number', '9', 'white', 70, 1, true),
  -- Currently 6 fixtures owned; growing to 10 soon — bump qty_owned when the rest arrive
  ('LED Uplighting', 'uplighting', null, null, null, 6, true),
  ('Stage', 'stage', null, null, null, 1, true),
  ('3D Arch', 'stage', null, null, null, 2, true);
